---

- name: Nginx reload
  service:
    name: nginx
    state: reloaded

- name: Systemctl reload
  command: systemctl daemon-reload

- name: Flask restart
  service:
    name: flask-srv
    state: restarted
