- name: Install iptables
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - iptables
    - iptables-persistent

- name: Iptables temporary set accept
  iptables:
    chain: INPUT
    policy: ACCEPT

- name: Iptables clean rules
  iptables:
    flush: true

- name: Iptables allow loopback
  iptables:
    action: append
    chain: INPUT
    in_interface: lo
    jump: ACCEPT

- name: Iptables allow established input connections
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- name: Iptables allow established output connections
  iptables:
    chain: OUTPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- name: Iptables allow established forward connections
  iptables:
    chain: FORWARD
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- name: Iptables allow ICMP
  iptables:
    chain: INPUT
    jump: ACCEPT
    protocol: icmp

- name: Iptables allow SSH
  iptables:
    chain: INPUT
    destination_port: 22
    jump: ACCEPT
    protocol: tcp

- name: Iptables allow HTTP
  iptables:
    chain: INPUT
    destination_port: 80
    jump: ACCEPT
    protocol: tcp

- name: Iptables allow HTTPS
  iptables:
    chain: INPUT
    destination_port: 443
    jump: ACCEPT
    protocol: tcp

- name: Iptables default drop in input chain
  iptables:
    chain: INPUT
    policy: DROP

- name: Iptables default drop in forward chain
  iptables:
    chain: FORWARD
    policy: DROP

- name: Iptables default drop in output chain
  iptables:
    chain: OUTPUT
    policy: ACCEPT

- name: Iptables save rules
  shell: iptables-save > /etc/iptables/rules.v4
